<?php

/**
 * @file
 * Manage a book group library of E-Books.
 */

/**
 * Implements Hook Menu.
 */
function bookgroup_menu() {
  $items = array();
  $items['bookgroup'] = array(
    'title' => t('Book Groups'),
    'description' => t('Manage an online Book Group'),
    'page callback' => 'bookgroup_entry',
    'access callback' => 'bookgroup_user_access',
    'access arguments' => array('bookgroup_access'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['bookgroup/groups'] = array(
    'title' => t('Book Groups'),
    'weight' => 10,
    'description' => 'Manage the Inventory of Imported Files and Tables.',
    'page callback' => 'bookgroup_groups',
    'access callback' => 'bookgroup_user_access',
    'access arguments' => array('group_access'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['bookgroup/libraries'] = array(
    'title' => t('Libraries'),
    'weight' => 20,
    'description' => 'Manage the Inventory of Imported Files and Tables.',
    'page callback' => 'bookgroup_libraries',
    'access callback' => 'bookgroup_user_access',
    'access arguments' => array('library_access'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['bookgroup/discussions'] = array(
    'title' => t('Discussions'),
    'weight' => 30,
    'description' => 'Manage the Inventory of Imported Files and Tables.',
    'page callback' => 'bookgroup_discussions',
    'access callback' => 'bookgroup_user_access',
    'access arguments' => array('discussion_access'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['bookgroup/members'] = array(
    'title' => t('Members'),
    'weight' => 40,
    'description' => 'Manage the Inventory of Imported Files and Tables.',
    'page callback' => 'bookgroup_members',
    'access callback' => 'bookgroup_user_access',
    'access arguments' => array('membership_access'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

function bookgroup_user_access($string='', $account = NULL) {
//  drupal_set_message('<pre>'.t('User Access: ').var_export($string,TRUE).
//                     "\n".t('acct: ').var_export($account,TRUE).'</pre>');
  $access = TRUE;

  return $access;
}

/**
 * Initial Module Entry.
 */
function bookgroup_entry() {
//  drupal_set_message(t('Got here.'));
  drupal_goto('bookgroup/groups');
}
/**
 * Bookgroup Dashboard
 */
function bookgroup_groups() {
//  drupal_set_message(t('Got to Groups.'));
  $data = new stdClass();
  
  $form = drupal_get_form('bookgroup_groups_form', $data);
  return drupal_render($form);
}
function bookgroup_groups_form($form, &$form_state, $data) {
  $form['submit'] = array(
    '#type' => 'submit',
//    '#attributes' => array('style'=>'visibility:hidden'),
    '#value' => t('Submit'),
  );  
  return $form;
}
function bookgroup_groups_form_validate($form, &$form_state) {
}
function bookgroup_groups_form_submit($form, &$form_state) {
}
/**
 * Bookgroup Libraries
 */
function bookgroup_libraries() {
  $data = new stdClass();
  
  $form = drupal_get_form('bookgroup_libraries_form', $data);
  return drupal_render($form);
}
function bookgroup_libraries_form($form, &$form_state, $data) {
  $form['submit'] = array(
    '#type' => 'submit',
//    '#attributes' => array('style'=>'visibility:hidden'),
    '#value' => t('Submit'),
  );  
  return $form;
}
function bookgroup_libraries_form_validate($form, &$form_state) {
}
function bookgroup_libraries_form_submit($form, &$form_state) {
}
/**
 * Bookgroup Discussions
 */
function bookgroup_discussions() {
  $data = new stdClass();
  
  $form = drupal_get_form('bookgroup_discussions_form', $data);
  return drupal_render($form);
}
function bookgroup_discussions_form($form, &$form_state, $data) {
  $form['submit'] = array(
    '#type' => 'submit',
//    '#attributes' => array('style'=>'visibility:hidden'),
    '#value' => t('Submit'),
  );  
  return $form;
}
function bookgroup_discussions_form_validate($form, &$form_state) {
}
function bookgroup_discussions_form_submit($form, &$form_state) {
}
/**
 * Bookgroup Memberships
 */
function bookgroup_members() {
  $data = new stdClass();
  
  $form = drupal_get_form('bookgroup_members_form', $data);
  return drupal_render($form);
}
function bookgroup_members_form($form, &$form_state, $data) {
  $form['submit'] = array(
    '#type' => 'submit',
//    '#attributes' => array('style'=>'visibility:hidden'),
    '#value' => t('Submit'),
  );  
  return $form;
}
function bookgroup_members_form_validate($form, &$form_state) {
}
function bookgroup_members_form_submit($form, &$form_state) {
}

